### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by arturjaworski** [drmohundro/SWXMLHash#108]
Hello,

Will be great if you add a support for Swift Package Manager. It will be possible to use the library without CocoaPods (eg. in command-line tools).

**Comment by arturjaworski** [comment]
Sorry, I've noticed that it is, but it's not documented.

**Comment by drmohundro** [comment]
@arturjaworski yeah, I haven't added documentation yet as most people working with SWXMLHash have been using either CocoaPods or Carthage. It seems like the Swift Package Manager could be used heavily on the Linux side of things, but SWXMLHash still doesn't fully work there because of https://bugs.swift.org/browse/SR-2301.

Are you interested in using the Swift Package Manager on the macOS side of things? I'd be happy to document it myself if so when I get some free time to (or accept a PR!).

**Comment by arturjaworski** [comment]
Thanks for answer!
I'm working on Swift command-line tool ([Colorizer](https://github.com/arturjaworski/Colorizer)). Swift command-line tools can't easily works with CocoaPods or Carthage. That's the reason why I asked about Swift Package Manager.
I would like to modify `.storyboard` file (I have to change some attributes only), but as I noticed it's not supported by `SWXMLHash` yet. I'm not sure when I'll be ready to implement next functionalities, but of course when I will consider some contribution related with it.

**Comment by steffendsommer** [comment]
Hi @drmohundro! Good job on the package. I'm interested in using it on Linux, but as I see it, the needed bug fix for Swift is not part of 3.0.2. Are there pieces of this package that would work on Linux (with Swift 3.0.2) at the moment, or do you suggest waiting for the next version of Swift to come out?

**Comment by drmohundro** [comment]
@steffendsommer good question... I honestly haven't used it on Linux. The unit tests are set up such that they _can_ run on Linux, but they're disabled at the moment because of the aforementioned bug. I'll periodically check out SR-2301, but you're correct - I don't think much of the library will work until that bug is resolved.
