### ISSUE TITLE
Parser stopped at "&" in element value. Following elements are missing

### ISSUE THREAD

**Issue by ischman** [drmohundro/SWXMLHash#109]
Input string:
`...<raumfeld:ebrowse>http://opml.radiotime.com/Tune.ashx?partnerId=7aJ9pvV5&formats=wma%2Cmp3%2Cogg&serial=123&id=123&c=ebrowse</raumfeld:ebrowse><dc:title>1LIVE diggi - Multimedia - 1LIVE</dc:title><raumfeld:durability>118</raumfeld:durability></item></DIDL-Lite>`

xml["DIDL-Lite"]["item"].all:
`...<raumfeld:ebrowse>http://opml.radiotime.com/Tune.ashx?partnerId=7aJ9pvV5</raumfeld:ebrowse></item>]`

Parser stopped at "&" in element value. Following elements are missing.

**Comment by drmohundro** [comment]
Is the `&` in a `CDATA` section? If not, it is likely not parsing because the underlying `NSXMLParser` is trying to treat it as an escaped character (e.g. like `&nbsp;` in HTML).

See http://stackoverflow.com/questions/730133/invalid-characters-in-xml as a reference.

If you wrap the link you're looking at in a CDATA section, it should also work.

**Comment by ischman** [comment]
Thanks!
Looks like the data i want to parse are not XML valid.
