### ISSUE TITLE
Possible problem when using SWXMLHash inside a framework

### ISSUE THREAD

**Issue by tkrajacic** [drmohundro/SWXMLHash#14]
Please have a look at https://github.com/tkrajacic/XMLTestWithFramework
It is a minimal crashing example.

When the application is finished processing the XML file it crashes when trying to over-release some CFString. This only happens when using a NSNumberFormatter to parse a String out of the XML.
When commenting out the String parsing, everything works.

I am not sure if I am making a mistake using SWXMLHash here or if it is a bug inside SWXMLHash.

Any help would be appreciated!

**Comment by drmohundro** [comment]
I've been digging on this for the better part of an hour tonight. I went off on a tangent because my understanding of Swift strings is that they are value types. But then I discovered that I could repro the bug by putting in a hardcoded number in the call to `NSNumberFormatter` meaning that it never even got a reference to `valueText`. That *really* threw me. The culprit? The call to `lowercaseString`.

If you change the `parseFromXMLNode` method in `XMLFormatter.swift` to only have the following, it will still blow up:

```swift
    mutating func parseFromXMLNode(xml: XMLIndexer) {
        
        self.name = xml[XMLKeys.name].element?.text
        
        let maybeUnit : String? = xml[XMLKeys.temperatureUnit].element?.text

        // this seems to cause the bug
        let bugRightHere = maybeUnit!.lowercaseString
    }
```

Does that make any sense to you? I'm curious if there might be a bug in the beta, because I thought I [read somewhere](http://airspeedvelocity.net/2015/02/11/changes-to-the-swift-standard-library-in-1-2-beta-1/) that `lowercaseString` and `uppercaseString` were moved back into Swift proper (as opposed to being in Framework).

**Comment by tkrajacic** [comment]
You sir are the man! I have tried so many variants and obviously must have overlooked this.
Now I feel really bad for letting you hunt down my programming mistakes :(
I'll take it to Apple's Swift Forums to see if one of the Swift guys has more to say about it, but I think you are right about the Swift String thingy.

**Comment by tkrajacic** [comment]
The bug seems to be documented already:

https://devforums.apple.com/message/1102272#1102272

**Comment by drmohundro** [comment]
No worries, I'm happy to help!
