### ISSUE TITLE
error: No such module 'SWXMLHash'

### ISSUE THREAD

**Issue by orodri** [drmohundro/SWXMLHash#142]
I cloned the repository and tried running the playground however I get the following error:

> Playground execution failed: error: SWXMLHashPlayground.playground:6:8: error: no such module 'SWXMLHash'
> import SWXMLHash
>        ^
> 
> 
> * thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 1.3
>   * frame #0: 0x0000000102bf03b0 SWXMLHashPlayground`executePlayground
>     frame #1: 0x0000000103701b5c CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
>     frame #2: 0x00000001036e6e54 CoreFoundation`__CFRunLoopDoBlocks + 356
>     frame #3: 0x00000001036e65ee CoreFoundation`__CFRunLoopRun + 894
>     frame #4: 0x00000001036e6016 CoreFoundation`CFRunLoopRunSpecific + 406
>     frame #5: 0x0000000108b16a24 GraphicsServices`GSEventRunModal + 62
>     frame #6: 0x0000000104268134 UIKit`UIApplicationMain + 159
>     frame #7: 0x0000000102bef6d9 SWXMLHashPlayground`main + 201
>     frame #8: 0x0000000106ca465d libdyld.dylib`start + 1

**Comment by drmohundro** [comment]
It looks like it is still working on my side, though I did have a tiny syntax error in the Playground code that I just corrected in master. Which version of Xcode are you using?

**Comment by orodri** [comment]
Xcode 8.3.3

Forgive me,

I was neglecting to open the Playground from within the Workspace. I thought opening the Playground by itself would work for some reason.

**Comment by drmohundro** [comment]
Ah, gotcha. That makes sense. Thanks for the update!

**Comment by jeeva-s** [comment]
hii im facing this issue in xcode Version 15.2 (15C500b) only in vs code but in xcode its working f9. How to solve this ?

**Comment by drmohundro** [comment]
Hi @jeeva-s, I suspect this is a slightly different problem as this issue was related to the Swift Playground. Regarding debugging, though, I suspect that the VS Code approach is using the Swift command line tools behind the scenes, though I'm not positive. Could you open a new issue and drop the details there along with the VS Code extension you're using? Also, I'd guess the extension has logs that show any command line output... those would probably help with diagnosing as well. Thanks!
