### ISSUE TITLE
How do I test whether an element exists when deserializing?

### ISSUE THREAD

**Issue by Zakirzhan** [drmohundro/SWXMLHash#162]
How do I test whether an element exists? We are always necessary to test whether an element exists before. Because can crash

For example:

```swift
extension News: XMLIndexerDeserializable {
    static func deserialize(_ node: XMLIndexer) throws -> News {
         return try News(
            title: node["title"].value(),
            pubDate: node["pubDate"].value(),
            imageUrl: node["image"]["url"].value(),
            sourceUrl: node["link"].value(),
            description: node["yandex:full-text"].value() )
    }
}
```

**Comment by drmohundro** [comment]
I tweaked your title, because I think you're specifically talking about during deserialization, at least based on your example.

In this case, you have a few options.

One would be to change your `News` object to take in a optional parameter (e.g. if title isn't always specified, then instead of `String` it might be `String?`). If the parameter is `String`, then that means that it should never be null; however, if your XML might allow for it to be nil, then the object should reflect that, too.

Alternatively, if instead all of the properties should be set but maybe have defaults if the XML doesn't provide them, then you could do something like this:

```swift
extension News: XMLIndexerDeserializable {
    static func deserialize(_ node: XMLIndexer) throws -> News {
        var title: String? = node["title"].value()
        if title == nil {
            title = "Some default value"
        }

        return try News(
            title: node["title"].value(),
            pubDate: node["pubDate"].value(),
            imageUrl: node["image"]["url"].value(),
            sourceUrl: node["link"].value(),
            description: node["yandex:full-text"].value() )
    }
}
```

The deserialization will set values to nil if the receiving variable is optional. You can see the tests for this at https://github.com/drmohundro/SWXMLHash/blob/master/Tests/SWXMLHashTests/TypeConversionBasicTypesTests.swift#L103-L110.

**Comment by drmohundro** [comment]
I'm going to go ahead and close this issue - let me know if you still have any questions. Thanks!
