### ISSUE TITLE
Optional value types

### ISSUE THREAD

**Issue by OgreSwamp** [drmohundro/SWXMLHash#187]
I have an XML where some elements can have no content, e.g.:
`<midname>Paul</midname>`
or 
`<midname/>`

if I'm parsing it with SWXMLHash to a `String?` I never get a `nil` as result. For `<midname/>` case the parser returns an empty `String`.

Example:
```
// parsing element <midname/>
var midname: String? = try element["midname"].value()
// midname value is ""
```

In `deserialize` method I wrote extra code to make sure optional has a nil value:
```
var midnameOpt: String? = try element["midname"].value()
if let midname = midnameOpt, midname.isEmpty {
    midnameOpt = nil
}
```

But I think that should be done automatically? Would you agree?

**Comment by drmohundro** [comment]
That is an interesting question... I totally understand what you're saying, too. There is conceptually a difference between `<midname></midname>` and `<midname />`. I'd have to research how other XML parsers treat that situation, whether one is an empty string or nil or not because I'd like to behave consistently there.

Regarding _why_, the underlying reason is that `XMLElement`'s `text` property is not nillable. See https://github.com/drmohundro/SWXMLHash/blob/master/Source/SWXMLHash.swift#L895-L903.

**Comment by drmohundro** [comment]
I think I'm going to pass on this feature - the parsers that I researched seem to treat empty elements as empty strings (versus null) aside from a few where you can optionally configure the `NULL` string to become null. If there are enough other requests, I might reconsider this, though.
