### ISSUE TITLE
Support of Swift 3

### ISSUE THREAD

**Issue by AlexeyShevchenko** [drmohundro/SWXMLHash#215]
Hey, 
I know that it is not an issue but anyway I did not find the way how I can install this cool framework in project which uses Swift 3. Could anybody help me with that?

**Comment by drmohundro** [comment]
Good question - I should probably add a version table or something to the documentation so that is more clear. So, [SWXMLHash 3.0.0](https://github.com/drmohundro/SWXMLHash/releases/tag/3.0.0) is the first release to support Swift 3.0, though I'd recommend using a more current version. To be honest, I *think* that from a Swift perspective, even the latest code should work with a Swift 3.0 codebase, but the Xcode changes might cause some issues.

Given that, are you stuck with a specific version of Xcode? As a follow up, are you using CocoaPods or Carthage or some other way of managing dependencies?

**Comment by AlexeyShevchenko** [comment]
Thanks for quick response!

Xcode 8.3.2
CocoaPods

**Comment by drmohundro** [comment]
Got it. I'd suggest starting out with version `3.1.0`, by doing this (replacing `YOUR_TARGET_NAME` with your project):

```
platform :ios, '10.0'
use_frameworks!

target 'YOUR_TARGET_NAME' do
  pod 'SWXMLHash', '~> 3.1.0'
end
```

I *think* you should be able to use `4.1.0` as well, but that was specifically coded against Swift 4, so I'm not 100% sure.

**Comment by ChrisMarshallNY** [comment]
Just FYI. I am integrating this excellent project into a Swift 5[.1] project.

The default CocoaPod for this (I only use it for my unit tests) is set for Swift 3.0.

I just go in there and bump up to 5.0 for all three projects, and it works -no problem.

**Comment by drmohundro** [comment]
Hey @ChrisMarshallNY - I'm not sure I'm following on which default CocoaPod... if you're referring to my notes above regarding targeting `~ 3.1.0`, then yes, but I'd recommend targeting version at least `'~> 4.7.0'` in your podspec per the readme.

Let me know if I'm misunderstanding your comment, though.

**Comment by ChrisMarshallNY** [comment]
It was really an informal bug report.

The three projects, when installed from the CocoaPod, are all set for Swift Language 3.0.

They break the build. I get a failure, indicating that Swift 3.0 is not supported.

I need to go in and set the language to 5.0 (I suppose 4.2 would work, but I just went straight to 5, and it worked).

**Comment by ChrisMarshallNY** [comment]
I'm not a CocoaPods genius (I generally don't like using it, but I will for testing/Linting stuff). It's possible that something I am doing is at fault.
