### ISSUE TITLE
Rename Framework

### ISSUE THREAD

**Issue by fgarciaDev** [drmohundro/SWXMLHash#242]
https://forums.swift.org/t/frameworkname-is-not-a-member-type-of-frameworkname-errors-inside-swiftinterface/28962

I have this issue when I create my XCFramework and the build tool generate my .swiftinterface files. With my dependency on `SWXMLHash` and a contained class of the same name, I run into the same issues found in the link above.

The short of it is that the classes in your framework are listed in the .swiftinterface file and the framework name is prepended. So XMLIndexerDeserializable becomes SWXMLHash.XMLIndexerDeserializable and Swift looks in the SWXMLHash class for XMLIndexerDeserializable.

The above link also contains a link to the issue to address, https://forums.swift.org/t/pitch-fully-qualified-name-syntax/28482, however, doesn't look like this will be available any time soon.

**Comment by drmohundro** [comment]
Sorry for the delay on the reply - I was having trouble following what the issue actually was. I found this reference on StackOverflow, though - see https://stackoverflow.com/questions/65798857/xcframeworks-swiftinterface-breaks-compile-when-imported-with-swift-package-ma.

So, if I'm understanding correctly, the suggestion is to rename the `SWXMLHash` class under the module to something else so that it doesn't conflict with the module. Is that right?

I don't have an issue with that, but it is definitely a breaking change. It looks like Alamofire did something similar to avoid this by renaming their main instance to `AF` so it is something other OSS libraries have run into.

It makes sense to me. Now, to come up with another name, though... `XMLHash` maybe?

**Comment by fgarciaDev** [comment]
Correct. From my understanding, it can be either a rename of the module/framework or the class itself. Unfortunately, either would be a breaking change. Appreciate your help on this. Would be happy to test with a commit SHA before you push a new release tag.

**Comment by drmohundro** [comment]
Sounds good to me. I'll see about getting a branch pushed up soon for testing and I'll drop the link here.

**Comment by drmohundro** [comment]
@fgarciaDev see my PR and branch up at https://github.com/drmohundro/SWXMLHash/pull/246. I just went with `XMLHash` for now. Let me know if it works for you.

**Comment by fgarciaDev** [comment]
@drmohundro Works great! Was able to add as a dependency to my framework without the need to manually edit the generated `*.swiftinterface` files.

**Comment by fp-fgarcia** [comment]
@drmohundro any traction with getting this pulled into a release?

**Comment by drmohundro** [comment]
@fp-fgarcia just pushed `6.0.0` - I gave it a few months, but there just wasn't a better solution still. In the PR, I linked to a few other conversations around similar name collision issues and there is an outstanding Swift bug that's been open for 5 years. I figure renaming is the best option at this point. Sorry for the delay!

**Comment by fp-fgarcia** [comment]
> @fp-fgarcia just pushed `6.0.0` - I gave it a few months, but there just wasn't a better solution still. In the PR, I linked to a few other conversations around similar name collision issues and there is an outstanding Swift bug that's been open for 5 years. I figure renaming is the best option at this point. Sorry for the delay!

Appreciate all the work! Thanks.
