### ISSUE TITLE
EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by ericrohlman** [drmohundro/SWXMLHash#39]
let parser = NSXMLParser(data: data)
parser.shouldProcessNamespaces = options.shouldProcessNamespaces
parser.delegate = self
parser.parse() ----> Line 227 - EXC_BAD_ACCESS (code=2, address=0x10f388000)

Occurs when running in iOS simulator

**Comment by drmohundro** [comment]
Can you post some code that reproduces this error so that I can see the full code (in particular the calling code) as well as the XML being passed in that is resulting in this error? The unit tests are still passing which exercises the `parse` method, so I suspect this is related to the XML being parsed. I can't tell for sure yet though.

**Comment by ericrohlman** [comment]
Figured it out– the XML wasn't in UTF8 format. Required a little data conversion. Excellent work on the util:

let convertedString = NSString(data: data, encoding: NSUTF8StringEncoding)
        if let convertedData = convertedString?.dataUsingEncoding(NSUTF8StringEncoding) {

**Comment by drmohundro** [comment]
:+1: Thanks for following up!
