### ISSUE TITLE
Please add swift 2 compatibility.

### ISSUE THREAD

**Issue by imran20487** [drmohundro/SWXMLHash#44]

**Comment by drmohundro** [comment]
Swift 2 compatibility is all in the [xcode-7.0 branch](https://github.com/drmohundro/SWXMLHash/tree/xcode-7.0). I'm keeping it in a branch as Xcode 7.0 is still in beta, but it will be mergeed into master once 7.0 is released.

Hope this helps.

**Comment by drmohundro** [comment]
Note that you can see the progress and related discussions on #31.

**Comment by AnthonyMDev** [comment]
@drmohundro Can this be merged now please? And hopefully a new pod version? thanks!

**Comment by drmohundro** [comment]
I'm not at a computer right now, but I'll plan to do it this evening (within the next 2-3 hours).

**Comment by AnthonyMDev** [comment]
Excellent. Thank you!

**Comment by drmohundro** [comment]
This is live now - the shield on the README still shows 1.1.0, but you can see the latest is up at https://cocoapods.org/pods/SWXMLHash.

**Comment by AnthonyMDev** [comment]
Thanks! I appreciate it!

**Comment by AnthonyMDev** [comment]
#outlook a {

padding: 0;
}
.ReadMsgBody {

width: 100%;
}
.ExternalClass {

width: 100%;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
.appleFooter a {

color: #999999;

text-decoration: none;
}
.faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
.mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

anthony.miller.csn@gmail.com sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Resources:

What is empowr?
Who's behind it?
See who you know that's on empowr

No more emails from anthony.miller.csn@gmail.com (anthony.miller.csn@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnSHhS9mAL8EFjbdccw1OkEAXwWPX7ygrerdkoZlMokWxmN4CQZ%2BgAZeg0ihvGveIeTPhkV2IAIsS4F25BOBqXZB0v5hTrlBZ4uJemuUL2T5oR6zKMUrHD8kUDiCaaNyRsh7y61ynXtoI&vet=694&mlid=8998534213&fn=QpLpyL23t7HpRXkzIHngtg%3D%3D

*This offer has been sent by anthony.miller.csn@gmail.com. By accepting this offer to try the new empowr, I stipulate that I'm 18 or older and am signing up having agreed with the product, terms and privacy policies, including the manner in which "$" and the word "earnings" are used throughout the empowr website, mobile apps and all empowr communications including this email, as defined in the product policy. This promotional email was sent to reply@reply.github.com and may contain special notices or offers. It is for illustrative purposes only and is in no way a guarantee. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA.

**Comment by AnthonyMDev** [comment]
#outlook a {

padding: 0;
}
.ReadMsgBody {

width: 100%;
}
.ExternalClass {

width: 100%;
}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
.appleFooter a {

color: #999999;

text-decoration: none;
}
.faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
.mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

Yesterday, anthony.miller.csn@gmail.com sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Not sure you know anthony.miller.csn@gmail.com?

View their photos  to see if you recognize them

Resources:

What is empowr?
Who's behind it?
See who you know that's on empowr

No more emails from anthony.miller.csn@gmail.com (anthony.miller.csn@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnSHhS9mAL8EFjbdccw1OkEAXwWPX7ygrerdkoZlMokWxmN4CQZ%2BgAZeg0ihvGveIeTPhkV2IAIsS4F25BOBqXZB0v5hTrlBZ4uJemuUL2T5oR6zKMUrHD8kUDiCaaNyRsh7y61ynXtoI&vet=694&mlid=9006522590&fn=QpLpyL23t7HpRXkzIHngtg%3D%3D

*This offer has been sent by anthony.miller.csn@gmail.com. By accepting this offer to try the new empowr, I stipulate that I'm 18 or older and am signing up having agreed with the product, terms and privacy policies, including the manner in which "$" and the word "earnings" are used throughout the empowr website, mobile apps and all empowr communications including this email, as defined in the product policy. This promotional email was sent to reply@reply.github.com and may contain special notices or offers. It is for illustrative purposes only and is in no way a guarantee. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA.

**Comment by AnthonyMDev** [comment]
#outlook a {

padding: 0;
}
ReadMsgBody {

width: 100%;
}
ExternalClass {

width: 100%;
}
ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {

margin: 0;

padding: 0;

}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
appleFooter a {

color: #999999;

text-decoration: none;
}
faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
mobile-only {

display: none;
}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 10px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

Just a friendly reminder that anthony.miller.csn@gmail.com sent you $20 to try the all-new empowr:

Receive your $20 &#9658;

Don't know anthony.miller.csn@gmail.com?

Return the $20  so it doesn't go to waste and you're not keeping anthony.miller.csn@gmail.com waiting

Resources:

What is empowr?
Who's behind it?
See who you know that's on empowr

No more emails from anthony.miller.csn@gmail.com (anthony.miller.csn@gmail.com)? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnSHhS9mAL8EFjbdccw1OkEAXwWPX7ygrerdkoZlMokWxmN4CQZ%2BgAZeg0ihvGveIeTPhkV2IAIsS4F25BOBqXZB0v5hTrlBZ4uJemuUL2T5oR6zKMUrHD8kUDiCaaNyRsh7y61ynXtoI&vet=694&mlid=9014749145&fn=QpLpyL23t7HpRXkzIHngtg%3D%3D

*This offer has been sent by anthony.miller.csn@gmail.com. By accepting this offer to try the new empowr, I stipulate that I'm 18 or older and am signing up having agreed with the product, terms and privacy policies, including the manner in which "$" and the word "earnings" are used throughout the empowr website, mobile apps and all empowr communications including this email, as defined in the product policy. This promotional email was sent to reply@reply.github.com and may contain special notices or offers. It is for illustrative purposes only and is in no way a guarantee. You can prevent future emails here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA.

**Comment by AnthonyMDev** [comment]
body {{ margin:0 !important; }}
div[style*="margin: 16px 0"] {{ margin:0 !important; font-size:100% !important; }}
#outlook a {{

padding: 0;
}}
.ReadMsgBody {{

width: 100%;
}}
.ExternalClass {{

width: 100%;
}}
.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {{

line-height: 100%;
}}
body, table, td, a {{

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}}
table, td {{

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}}
img {{

-ms-interpolation-mode: bicubic;
}}

body {{margin: 0;padding: 0;}}
img {{

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}}
table {{

border-collapse: collapse !important;
}}
body {{

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}}

appleBody a {{

color: #68440a;

text-decoration: none;
}}
.appleFooter a {{

color: #999999;

text-decoration: none;
}}
.faq {{

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}}
.mobile-only {{

display: none;
}}
.img-apps {{ padding:0 5px 0 0;}}

a.mobile-button:link, a.mobile-button:visited {{ color:#fff!important;}}

@media screen and (max-width: 525px) {{

table[class="wrapper"] {{

width: 100% !important;
}}

td[class="logo"] {{

text-align: left;

padding: 20px 0 20px 0 !important;
}}
td[class="logo"] img {{

margin: 0 auto!important;
}}

[class="mobile-only"] {{

display: block;
}}

br[class="mobile-hide"] {{

display: none;
}}
td[class="mobile-hide"] {{

display: none;
}}
img[class="mobile-hide"] {{

display: none !important;
}}
img[class="img-max"] {{

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}}

img[class="img-min"] {{

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}}

img[class="img-apps"] {{

max-width: 46% !important;

width: 46% !important;

height: auto !important;

padding:0 2px;
}}
img[class="img-max-profile"] {{

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}}

table[class="responsive-table"] {{

width: 100%!important;
}}

td[class="padding"] {{

padding: 10px 5% 15px 5% !important;
}}
td[class="amount"] {{

font-size: 9px!important;
}}
td[class="mobile-text-twelve"] {{

font-size: 12px!important;
}}
span[class="mobile-text-twelve"] {{

font-size: 14px!important;
}}
td[class="padding-copy"] {{

padding: 10px 5% 10px 5% !important;

text-align: center;
}}
td[class="padding-meta"] {{

padding: 30px 5% 0px 5% !important;

text-align: center;
}}
td[class="no-pad"] {{

padding: 0 0 20px 0 !important;
}}
td[class="no-pad-bottom"] {{

padding: 25px 0 0 0 !important;
}}
td[class="no-padding"] {{

padding: 0 !important;
}}
td[class="section-padding"] {{

padding: 25px 15px 25px 15px !important;
}}
td[class="section-no-padding-bottom"] {{

padding: 25px 15px 0 15px !important;
}}

td[class="section-no-padding-top"] {{

padding: 0 5% 25px 5% !important;
}}

td[class="section-no-padding-top-bottom"] {{

padding: 0 5% 0 5% !important;
}}
td[class="section-padding-bottom-image"] {{

padding: 50px 15px 0 15px !important;
}}

td[class="mobile-wrapper"] {{

padding: 10px 5% 15px 5% !important;
}}
table[class="mobile-button-container"] {{

margin: 0 auto;

width: 100% !important;
}}
a[class="mobile-button"] {{

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}}
}}

Earn $100 in 1 minute.

How?

Simply try our new social network for only 50 seconds...

..and give us your feedback in less than 10 seconds.

Give me $100 (start the clock) &#9658;

Your empowr account was reserved for you by anthony.miller.csn@gmail.com. In order to store your gift however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything.

While your account is very new, if you fail to sign in for just a few days, it will be deleted to eliminate unwanted emails for you, so click a button in emails periodically to notify the system of your desire to keep it active. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnSHhS9mAL8EFjbdccw1OkEAXwWPX7ygrerdkoZlMokWxmN4CQZ%2BgAZeg0ihvGveIeTPhkV2IAIsS4F25BOBqXZB0v5hTrlBZ4uJemuUL2T5oR6zKMUrHD8kUDiCaaNyRsh7y61ynXtoI&vet=724&mlid=9313829617.

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: empowr Terms and Conditions. You can prevent future emails here. You can change your password here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA

**Comment by AnthonyMDev** [comment]
body { margin:0 !important; }
div[style*="margin: 16px 0"] { margin:0 !important; font-size:100% !important; }
#outlook a {

padding: 0;
}
ReadMsgBody {

width: 100%;
}
ExternalClass {

width: 100%;
}
ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {

line-height: 100%;
}
body, table, td, a {

-webkit-text-size-adjust: 100%;

-ms-text-size-adjust: 100%;
}
table, td {

mso-table-lspace: 0pt;

mso-table-rspace: 0pt;
}
img {

-ms-interpolation-mode: bicubic;
}

body {margin: 0;padding: 0;}
img {

border: 0;

height: auto;

line-height: 100%;

outline: none;

text-decoration: none;
}
table {

border-collapse: collapse !important;
}
body {

height: 100% !important;

margin: 0;

padding: 0;

width: 100% !important;
}

appleBody a {

color: #68440a;

text-decoration: none;
}
appleFooter a {

color: #999999;

text-decoration: none;
}
faq {

line-height: 18px;

list-style: outside none none;

margin: 10px 0;

padding: 0;
}
mobile-only {

display: none;
}
img-apps { padding:0 5px 0 0;}

a.mobile-button:link, a.mobile-button:visited { color:#fff!important;}

@media screen and (max-width: 525px) {

table[class="wrapper"] {

width: 100% !important;
}

td[class="logo"] {

text-align: left;

padding: 20px 0 20px 0 !important;
}
td[class="logo"] img {

margin: 0 auto!important;
}

[class="mobile-only"] {

display: block;
}

br[class="mobile-hide"] {

display: none;
}
td[class="mobile-hide"] {

display: none;
}
img[class="mobile-hide"] {

display: none !important;
}
img[class="img-max"] {

max-width: 100% !important;

width: 100% !important;

height: auto !important;
}

img[class="img-min"] {

max-width: 73px !important;

width: 73px !important;

height: auto !important;

padding-top: 8px !important;
}

img[class="img-apps"] {

max-width: 46% !important;

width: 46% !important;

height: auto !important;

padding:0 2px;
}
img[class="img-max-profile"] {

max-width: 50% !important;

width: 50% !important;

height: auto !important;

border-radius: 200px;
}

table[class="responsive-table"] {

width: 100%!important;
}

td[class="padding"] {

padding: 10px 5% 15px 5% !important;
}
td[class="amount"] {

font-size: 9px!important;
}
td[class="mobile-text-twelve"] {

font-size: 12px!important;
}
span[class="mobile-text-twelve"] {

font-size: 14px!important;
}
td[class="padding-copy"] {

padding: 10px 5% 10px 5% !important;

text-align: center;
}
td[class="padding-meta"] {

padding: 30px 5% 0px 5% !important;

text-align: center;
}
td[class="no-pad"] {

padding: 0 0 20px 0 !important;
}
td[class="no-pad-bottom"] {

padding: 25px 0 0 0 !important;
}
td[class="no-padding"] {

padding: 0 !important;
}
td[class="section-padding"] {

padding: 25px 15px 25px 15px !important;
}
td[class="section-no-padding-bottom"] {

padding: 25px 15px 0 15px !important;
}

td[class="section-no-padding-top"] {

padding: 0 5% 25px 5% !important;
}

td[class="section-no-padding-top-bottom"] {

padding: 0 5% 0 5% !important;
}
td[class="section-padding-bottom-image"] {

padding: 50px 15px 0 15px !important;
}

td[class="mobile-wrapper"] {

padding: 10px 5% 15px 5% !important;
}
table[class="mobile-button-container"] {

margin: 0 auto;

width: 100% !important;
}
a[class="mobile-button"] {

width: 80% !important;

padding: 15px !important;

border: 0 !important;

font-size: 16px !important;
}
}

has invited you to this exclusive free trial
http://www.empowr.com/Navigation/RegistrationWelcome.aspx?Action=ReferralInstantRegistration&amp;RegistrationFlowFlavor=15&amp;authToken=%2f1gCEGV9d6c%2bVY%2b1oJCzGJUNklVdNk5hG5iyEJ2gj1g9yoho8VwPsXR81BOuRzBWLUSORioeXpb%2fsZ8rmbPoyk7g2Ds6Q%2f5PgvnGGZmElhGVgCpJv8vnl321ClLSfe3m0gDEQAKbOgLS6Qwx8EJKWjY4e%2b9PhsEh8Gsf0IBBrP2KIClUkdM%2bZXZPq%2fttiQFd6s3U6MVWOMcpNtWR1C2PDJZRz8hn8ht3H3OwqLXa%2fyHFWtdeMALTBFCqJqR9qAYJEkFnYgwce1ijrljdLN%2bYMtWEmNaCPRlPojOaWPFfjuyQ9afUEF6m%2fXRHZv9OsQTE&amp;PolicyAcceptance=hS9jQifr3fBH%2bKMoUM3K%2fVU2tv0EdFG%2bbo3Yz%2fYAc%2fplMUi0N4Nnc5ULQs6pcqBpYSMqNebzFLEjGwCWMoowy9l%2bKwNnqyHf8pn%2fhk6JkdU8%2b4zTREXV9jV%2bWg6canudd4%2fubg1ZuEMJJacyOsuLaUmunRmEIZ7GJ7Y8I8d%2bdMb5vELoNxwtOtr6%2fnwSHunRb%2fzBV9jlnnP1XWEX7K3evjxb%2b%2f4obj%2bCXj0UmJevwrxiy25bbPtFT50JVSIN7Ru00%2f2FxHBPoRjkgJ1A8ERM6pDwlxWUGyCILk9RzqpkyoEGqpqKcW5PIAGgaRFduL%2fIOhc1Nksou7Amy2VS3vLQuIyLX41Eq9Czzw%2b1dFzsekQ5ZxJ5AJeoa3zz7NX1sNx5ZwOOCfgmO0Rh6LmoaYYvsIQTi97zfLAmAcJR8pkQS2soLvenLYilci8oR7fpI2vhqJ2n64bz9OM0ac%2fBj0vovxOAqW5ZZAYmW7Wcj1RPLpAohEP8SzdPPuLMIGW%2bwpuMnbTnn2T9tze5mCwyeSjuUSrVU4Q0AfJMl%2bHVn1D7F%2fvmCZ9CMWWE%2bQT5Gww40fgyCn%2bTPJuTa5YCbGLp41nmcdgBqY6nUq29DkPH%2bZO5Nwm%2bGTR41i4fDYCUo36jclUSvDaQazAhIh0D7LYwH%2fJxxO0vRrzFFF9awOkDejP3tiYYGbT0oSnUy06mYF58ad4vEeq64XFO3nBuRZvQgcdiCRDmSuMG0QHHq5zPoSEGMW455Xn35hZV4hE7aYdqCXnGNqVfzhLAQYpoK%2bnUvyebXN2oLQfxt8X2PBy3mNUXBd2O%2bHKB6tshtxy0fN7NOIDJVkpKgjmYjR7R6yFussqF3DvOJi5%2btvDs2z1nWKbXQYeHDRIRWMJOR%2fz9v0OhR%2f3ibiJxS5ZSX1pFPwgv9DCCEHnYeXAX6qxv2gSNb7bqPHXpG%2fFCG03WvrN0vKEGqmFCFkaRhcUd3RCH69GIv6uuAQ%3d%3d&amp;vet=745&amp;dt=111817&amp;mlid=10031189298&amp;tmpID=3340&amp;linkname=InviteLink&amp;pt=0&amp;esp=0&amp;eaid=40457925&amp;rt=12:

Your account was reserved for you by  in order to reserve your free trial, however you must agree to terms and validate before it can be created.

By accessing your account via the links or buttons in this email, you're both validating your email and stipulating that you're 18 or older and are signing up having agreed with the product, terms and privacy policies, including the manner in which "$", "earnings", maturation and advertising are used or applied throughout the empowr products and communications.

Earnings are virtual currency revenues, not profits; are for illustrative purposes only and are in no way a guarantee of anything. You can manually delete your account and/or block future invitations from here
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnSHhS9mAL8EFjbdccw1OkEAXwWPX7ygrerdkoZlMokWxmN4CQZ%2BgAZeg0ihvGveIeTPhkV2IAIsS4F25BOBqXZB0v5hTrlBZ4uJemuUL2T5oR6zKMUrHD8kUDiCaaNyRsh7y61ynXtoI&vet=745&mlid=10031189298.

No more emails from  ()? Unsubscribe
http://profile.empowr.com/ApplicationManager/CommunityEmailSettings.aspx?em=K%2FzdUVCDppRybzAPzsRVnSHhS9mAL8EFjbdccw1OkEAXwWPX7ygrerdkoZlMokWxmN4CQZ%2BgAZeg0ihvGveIeTPhkV2IAIsS4F25BOBqXZB0v5hTrlBZ4uJemuUL2T5oR6zKMUrHD8kUDiCaaNyRsh7y61ynXtoI&vet=745&mlid=10031189298

*This promotional email was sent to reply@reply.github.com and may contain special notices or offers. To see current terms and conditions visit: empowr Terms and Conditions. You can prevent future emails here. You can change your password here. empowr - 501 West Broadway, Suite A182, San Diego, CA 92101, USA

**Comment by drmohundro** [comment]
I'm locking this issue to try to prevent the automated emails coming in (like the one above). I've been deleting them, but I'm just going to lock at this point.
