### ISSUE TITLE
Issue when return string

### ISSUE THREAD

**Issue by VitoPietrapertosa** [drmohundro/SWXMLHash#87]
Hi,
when I try to print some text value , it return optional(" ----text   ")
for example if I have this xml: 
`<root>`
  ...
  `<catalog>`
    `<book>`<author>`Bob`</author>`</book>`
    `<book>`<author>`John`</author>`</book>`
   `<book>`<author>`Mark`</author>`</book>`
  `</catalog>`
  ...
`</root>`

when I try to print    xml["root"]["catalog"]["book"][1]["author"].element?.text

the output is   optional( "              John           ")   instade of   "John".

Any idea?

**Comment by gca3020** [comment]
@VitoPietrapertosa It looks like your XML has spaces, so the parser is doing what it should. If you want to trim the spaces, you can do that yourself. Have a look [here](http://stackoverflow.com/questions/26797739/does-swift-has-trim-method-on-string) for a Swift 2 solution, but keep in mind this will likely change a bit for Swift 3. 

Regarding the Optional() bit, this is because element?.text is going to return a Swift optional. Best practice is to make sure it exists with an "if let" statement, but if you are 100% sure that it will be there, you can use forced unwrapping with an '!' character. See [here](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/OptionalChaining.html) for more details on Swift Optional chaining.

**Comment by drmohundro** [comment]
@VitoPietrapertosa FYI, I'm going to go ahead and close this issue - if you're still having problems, feel free to re-open and post some additional details. Thanks!
